# Generated by Django 4.0.6 on 2022-08-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0002_client_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='meeting_date',
            field=models.DateField(),
        ),
    ]
