# Generated by Django 4.0.6 on 2022-08-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0004_alter_client_age_alter_client_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='meeting_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
